{
 "title": "Drift Dashboard",
 "time": { "from": "2023-12-01T00:00:00.000Z", "to": "2023-12-05T00:00:00.000Z" },
 "panels": [
  {
   "title": "Drift Test for Individual Features",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "windspeed Drift Score",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "select timestamp, windspeed_drift_score\nfrom data_drift_metrics;"
    }
   ]
  },
  {
   "title": "Holiday Drift Score",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "select timestamp, holiday_drift_score        \nfrom data_drift_metrics;"
    }
   ]
  },
  {
   "title": "atemp Drift Score",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "select timestamp, atemp_drift_score\nfrom data_drift_metrics;"
    }
   ]
  },
  {
   "title": "Weathers Drift Score",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "rawSql": "select timestamp, weathersit_drift_score\nfrom data_drift_metrics;"
    }
   ]
  },
  {
   "title": "Temp Drift Score",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "rawSql": "select timestamp, temp_drift_score\nfrom data_drift_metrics;"
    }
   ]
  },
  { "title": "Target Drift", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Target Drift Score",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "select timestamp, target_drift_score\nfrom data_drift_metrics;"
    }
   ]
  },
  { "title": "Dataset Level Drift Test", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Dataset Level Drift Score",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "select timestamp, dataset_drift_score\nfrom data_drift_metrics;"
    }
   ]
  },
  {
   "title": "Important Features Drift Score",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "rawSql": "select timestamp, imp_var_drift_score\nfrom data_drift_metrics;"
    }
   ]
  }
 ]
}